language: objective-c
osx_image: xcode10.1
script:
    - xcodebuild clean test -project 'Hotels booking.xcodeproj' -scheme 'Hotels booking' -destination "platform=iOS Simulator,OS=12.1,name=iPhone X" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet