{
  "script": "set -o pipefail && xcodebuild test -workspace \"${TRAVIS_XCODE_WORKSPACE}\" -scheme \"${TRAVIS_XCODE_SCHEME}\" -sdk \"${TRAVIS_XCODE_SDK}\" | xcpretty",
  "language": "objective-c",
  "osx_image": "xcode8",
  "xcode_sdk": "iphoneos9.3",
  "xcode_scheme": "Travis CI"
}  